<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net462;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Description>Enterprise Pure C# Video Streaming, RTSP Transport, H.264 NAL Parser &amp; Multimedia Engine for .NET.</Description>
    <PackageTags>video;rtsp;rtp;h264;multimedia;streaming;framebuffer;yuv</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ZeroPrimitives\src\ZeroPrimitives.Core\ZeroPrimitives.Core.csproj" />
  </ItemGroup>
</Project>
